'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("formulario.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _17726514_Personaje_de_dibujos_animados_de_naranja_con_candado_y_llave_de_oro_Fondo_blanco__Foto_de_archivo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("17726514-Personaje-de-dibujos-animados-de-naranja-con-candado-y-llave-de-oro-Fond"& _ 
                        "o-blanco--Foto-de-archivo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _61299bd8cea71352b615bb685b2ce9a4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("61299bd8cea71352b615bb685b2ce9a4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6777eea7c27ae3e85141662d6a130d91_16b85579d9bccc169da24548ba0d39_clipart_bloc_notes_1300_1298() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6777eea7c27ae3e85141662d6a130d91_16b85579d9bccc169da24548ba0d39-clipart-bloc-note"& _ 
                        "s_1300-1298", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8624081_colorful_city_downtown_icon_of_tall_commercial_buildings_vector_graphic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8624081-colorful-city-downtown-icon-of-tall-commercial-buildings-vector-graphic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _87971363() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("87971363", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _893cff7168a318ddfba5c0d0bef8deec() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("893cff7168a318ddfba5c0d0bef8deec", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property calcul() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calcul", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property depositphotos_110652234_stock_illustration_dices_sign_icon_casino_game() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("depositphotos_110652234-stock-illustration-dices-sign-icon-casino-game", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dinero_simbolo_grafico_de_presentacion_318_60690() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dinero-simbolo-grafico-de-presentacion_318-60690", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eliminar_x_roja_mundo_10_4399() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eliminar-x-roja-mundo_10-4399", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forma_de_ojo_de_cerradura_en_un_cuadrado_negro_318_52988() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forma-de-ojo-de-cerradura-en-un-cuadrado-negro_318-52988", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hourglass_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hourglass-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imagenes_cruz_verde_081b4ab9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imagenes_cruz_verde_081b4ab9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property símbolo_plano_de_la_llave_de_la_reparación_del_vector_de_la_muestra_del_diente_de_los_ajustes_49638817() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("símbolo-plano-de-la-llave-de-la-reparación-del-vector-de-la-muestra-del-diente-de"& _ 
                        "-los-ajustes-49638817", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
